package com.personal_projects.order_service.order;

import com.personal_projects.common.Enums.OrderStatus;
//import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
//@Entity
//@Table
public class Order {
//    @Id
//    @SequenceGenerator(
//            name = "order_sequence",
//            sequenceName = "order_sequence",
//            allocationSize = 1
//    )
//    @GeneratedValue(
//            strategy = GenerationType.SEQUENCE,
//            generator = "order_sequence"
//    )
    private String id; // UUID or autogenerated
    private String customerName;
    private String productName;
    private int quantity;
    private double price; // per unit
    private double totalAmount;
    private OrderStatus status; // Enum: CREATED, PAID, SHIPPED
    private LocalDateTime createdAt;
}
