package com.personal_projects.order_service.order;

import com.personal_projects.common.Enums.OrderStatus;
import lombok.*;

import java.time.LocalDateTime;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Order {
    private String id; // UUID or autogenerated
    private String customerName;
    private String productName;
    private int quantity;
    private double price; // per unit
    private double totalAmount;
    private OrderStatus status; // Enum: CREATED, PAID, SHIPPED
    private LocalDateTime createdAt;
}
